# =============================================================================
synthetic:
  meta:
    project_id: "EMB_ex12-S"
    current_version: "v1.0"
    researcher: "DK"


  network:
    avg_k: [20]
    gamma: [2.1, 2.5, 2.9, 3.5]
    mu: [0.1] #, 0.2, 0.3, 0.4, 0.5]


  experiment:
    params:
      pfis: [0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 0.95]
      metrics: ["inverse", "negexp"]
      repetitions: 3

    hyperparams:
      method: "LE"
      dimension: 40
      maxiter_multiplier: 100 # 0
      tol_exp: -8 # 1 (-Inf)


  workflow:
    pathing:
      input:
        raw: "{root}/data/input/raw"
        preprocessed: "{root}/data/input/preprocessed/synthetic"
      output:
        raw: "{root}/data/output/raw"
        preprocessed: "{root}/data/output/processed/synthetic"
      result:
        dataframe: "{root}/results/dataframes"
        figures: "{root}/results/plots"
        reports: "{root}/results/reports"
      scripts: "./scripts/"

    datafiles:
      input:
        duplex: "{dir}/LFR_N=10000_avgk={{avg_k}}_mu={{mu}}_gamma={{gamma}}_tau=1.0_rep={{rep}}.pkl"
      output:
        observation: "{dir}/observed_pfi={{pfi}}_LFR_N=10000_avgk={{avg_k}}_mu={{mu}}_gamma={{gamma}}_tau=1.0_rep={{rep}}.pkl"
        vectors: "{dir}/vectors_pfi={{pfi}}_LFR_N=10000_avgk={{avg_k}}_mu={{mu}}_gamma={{gamma}}_tau=1.0_rep={{rep}}.pkl"
        distances: "{dir}/distances_pfi={{pfi}}_LFR_N=10000_avgk={{avg_k}}_mu={{mu}}_gamma={{gamma}}_tau=1.0_rep={{rep}}.pkl"
        reconstruction: "{dir}/reconstruction_metric={{metric}}_pfi={{pfi}}_LFR_N=10000_avgk={{avg_k}}_mu={{mu}}_gamma={{gamma}}_tau=1.0_rep={{rep}}.pkl"
        record: "{dir}/record_metric={{metric}}_pfi={{pfi}}_LFR_N=10000_avgk={{avg_k}}_mu={{mu}}_gamma={{gamma}}_tau=1.0_rep={{rep}}.pkl"
      result:
        dataframe: "{dir}/dataframe_{project_id}{current_version}_{researcher}_{date}.parquet"
        report: "{dir}/report_{project_id}{current_version}_{researcher}_{date}.html"
        dag: "{dir}/dag_{project_id}{current_version}_{researcher}_{date}.svg"
        figures:
          scatter: "{dir}/scatter_{project_id}{current_version}_{researcher}_{date}.png"


# =============================================================================
real:
  meta:
    project_id: "EMB_ex12-R"
    current_version: "v1.0"
    researcher: "DK"


  network:
    arxiv:
      layers: [2, 6, 7] # [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
    celegans:
      layers: [1, 2, 3]
    drosophila:
      layers: [1, 2, 3] # [1, 2, 3, 4, 5, 6, 7]
    london:
      layers: [1, 2, 3]


  experiment:
    params:
      pfis: [0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 0.95]
      metrics: ["inverse", "negexp"]
      repetitions: 5

    hyperparams:
      method: "LE"
      dimension: 40
      maxiter_multiplier: 100 # 0
      tol_exp: -8 # 1 (-Inf)



  workflow:
    pathing:
      input:
        raw: "{root}/data/input/raw"
        preprocessed: "{root}/data/input/preprocessed/real"
      output:
        raw: "{root}/data/output/raw"
        preprocessed: "{root}/data/output/processed/real"
      result:
        dataframe: "{root}/results/dataframes"
        figures: "{root}/results/plots"
        reports: "{root}/results/reports"
      scripts: "./scripts/"

    datafiles:
      input:
        duplex: "{dir}/duplex_system={{system}}.edgelist"
      output:
        observation: "{dir}/observed_pfi={{pfi}}_system={{system}}_alpha={{alpha}}_beta={{beta}}_rep={{rep}}.pkl"
        vectors: "{dir}/vectors_pfi={{pfi}}_dimension={{dimension}}_system={{system}}_alpha={{alpha}}_beta={{beta}}_rep={{rep}}.pkl"
        distances: "{dir}/distances_pfi={{pfi}}_dimension={{dimension}}_system={{system}}_alpha={{alpha}}_beta={{beta}}_rep={{rep}}.pkl"
        reconstruction: "{dir}/reconstruction_metric={{metric}}_pfi={{pfi}}_dimension={{dimension}}_system={{system}}_alpha={{alpha}}_beta={{beta}}_rep={{rep}}.pkl"
        record: "{dir}/record_metric={{metric}}_pfi={{pfi}}_dimension={{dimension}}_system={{system}}_alpha={{alpha}}_beta={{beta}}_rep={{rep}}.pkl"
      result:
        dataframe: "{dir}/dataframe_{project_id}{current_version}_{researcher}_{date}.parquet"
        report: "{dir}/report_{project_id}{current_version}_{researcher}_{date}.html"
        dag: "{dir}/dag_{project_id}{current_version}_{researcher}_{date}.svg"
        figures:
          scatter: "{dir}/scatter_{project_id}{current_version}_{researcher}_{date}.png"
