metadata:
  id: "EMB_ex38"
  version: "v0.1"
  researchers: "DK"
  protocol: True
  protocol_from_root: ["workflow", "operative", "active", "ex38", "procotol_EMB_ex38.md"]

dev:
  logging:
    directory_from_root: [".logs", ""]
    filelogger:
      filepath: "log__{datetime.today().strftime('%Y%m%d')}.log"  # NOTE: Will use .format() in setup
      mode: "w"
      level: 10
    consolelogger:
      level: 20
  console:
    tqdm: True
    warnings_filter: True


hyperparameters:
  workflow:
    directories:
      root: ["..", "..", "..", "..", ""]  # Note: Relative to this config file!
      scripts_from_root: ["scripts", "snakemake", ""]
      caches_from_root: ["data", "input", "caches", ""]
      models_from_root: ["data", "output", "models", ""]
      reconstructions_from_root: ["data", "output", "reconstructions", ""]
      dataframes_from_root: ["data", "output", "dataframes", ""]
      figures_from_root: ["data", "output", "figures", ""]
      reports_from_root: ["results", "reports", ""]
    reports:
      rulegraph: True
      report: True
    clean:
      models: False
      reconstructions: True
  env: False


parameters:  # default to always including intercept, see logreg params
  features: [
    # ["emb"],
    # ["deg"],
    ["emb", "deg"]
  ]

  # ! This should all be off-loaded?
  caches:  # check inclusion
    embedding:
      embedder: "N2V"
      PC: True
      dimensions: [128]
    network:
      system: "LFR"
      N: [1000]
      t1: [2.1]
      t2: [1.0]
      mu: [0.1]
      kavg: [6]
      kmax: [31]

  logistic_regression:  # pass as kwargs
    fit_intercept: True
    solver: "newton-cholesky"
    penalty: "none"
