network:
  N: [100, 1000, 10000]
  gamma: [2.0, 2.25, 2.50, 2.75, 3.0]
  kmin: [3, 8, 15]
  prob: [0.0, 0.20, 0.40, 0.60, 0.80, 1.0]
  sign: [-1, 1]
  pfi: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95]
  repetition: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

embedding:
  dimensions: 128
  walk_length: 30
  num_walks: 200
  workers: 4
  window: 10
  min_count: 1
  batch_words: 4

workflow:
  datafiles:
    KEEP_EMBEDDINGS: True
    TEMPLATE: ""
  pathing:
    SRC: "src/"
    TMP: ".tmp/"
    RAW: "results/raw/"
    PROCESSED: "results/processed/"
    FIGURES: "results/plots/"