network:
  N: [1000, 5000, 10_000]
  tau1: [2.1, 2.5, 2.9]
  tau2: [1.0]
  mu: [0.1, 0.3, 0.75]
  avg_k: [5, 12]
  min_community: [10, 100]
  prob: [1.0]
  pfi: [0.00, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 0.95]

experiment:
  params:
    repetitions: [1,2,3,4,5]
    largest_component: True
    distance: ["inverse", "negexp", "logistic"]
  embedding:
    dimensions: 128
    walk_length: 30
    num_walks: 100
    workers: 24
    window: 10
    min_count: 1
    batch_words: 4

workflow:
  datafiles:  # templates should not include extensions
    KEEP_EMBEDDINGS: False
    KEEP_DATAFRAME: True
    TEMPLATE_DF: "{project_id}{current_version}_{researcher}_{date}"
    TEMPLATE_VECTORS: "{tmp}/raw_N={N}_tau1={tau1}_tau2={tau2}_mu={mu}_avgk={avg_k}_prob={prob}_pfi={pfi}_repetition={repetition}_prob-model_{distance}.mat"
  pathing:  # must be relative to workflow scripts/notebooks
    SCRIPTS: "scripts/"
    TMP: "/tmp/EmbeddedNaive/"
    RAW: "../results/raw/"
    PROCESSED: "../results/processed/"
    FIGURES: "../results/plots/"
  versioning:
    project_id: "EMB_ex04"
    current_version: "v4.1"
    researcher: "DK"