# =========== BUILD ===========
[build-system]
build-backend = 'setuptools.build_meta'
requires = [
    'setuptools',
]

# ========== PROJECT ==========
[project]
name = "embmplxrec"
authors = [
    {name="Daniel Kaiser", email="kaiserd@iu.edu"},
]
description = "[Description]"
classifiers = ["License :: MIT License"]
requires-python = ">=3.10"
dependencies = [
    "networkx>=2.8",
    "numpy>=1.23",
    "pandas>=1.4",
    "scipy>=1.9",
    "scikit-learn>=1.2"
]
dynamic = ["version", "readme"]

[project.optional-dependencies]
test = [
    "pytest>=7"
]
reproduce = [
    "snakemake",
    "matplotlib",
    "seaborn"
]

# ========== DOCS ===========
[project.urls]
"Homepage" = "https://github.com/kaiserd/proj_naive-embedded-reconstruction"
"Bug Tracker" = "https://github.com/kaiserd/proj_naive-embedded-reconstruction/issues"


# ========== METADATA ===========
[tool.setuptools.dynamic]
version = {attr = "embmplxrec.VERSION"}
readme = {file = ["README.md"]}