network:
  gamma: [2.1]
  mu: [0.1, 0.2, 0.3, 0.4, 0.5]


experiment:
  params:
    pfi: [0.00, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 0.95]
    metrics: ["inverse", "negexp"]
    largest_component: False
    repetitions: 5

  hyperparams:
    embedding:
      dimensions: 128
      walk_length: 30
      num_walks: 100
      workers: 4
      window: 10
      min_count: 1
      batch_words: 4

workflow:
  # Templates should _not_ include file extensions
  datafiles:
    input:  # Meant to be treated as wildcards!
      duplex: "LFR_N={N}_avgk={avgk}_mu={mu}_gamma={gamma}_tau={tau}_rep={rep}"
      observed: "observed_LFR_N={N}_avgk={avgk}_mu={mu}_gamma={gamma}_tau={tau}_rep={rep}_pfi={pfi}"
    output:
      df: "{loc}/data-dataframe_{project_id}{current_version}_{researcher}_{date}"
      vectors: "{loc}/data-embeddings_{project_id}{current_version}_{researcher}_{date}"
    meta:
      report: "{loc}/workflow-report_{project_id}{current_version}_{researcher}_{date}"
      dag: "{loc}/workflow-dag_{project_id}{current_version}_{researcher}_{date}"

  # Paths must be relative to Snakefile
  pathing:
    raw_data: "../../data/input/preprocessed/synthetic/"
    preprocessed_data: "../../data/input/preprocessed/"
    temp: "../.tmp/"

    raw: "../../results/raw/"
    processed: "../../results/processed/"
    figures: "../../results/plots/"
    reports: "../../results/reports/"

    scripts: "scripts/"

  versioning:
    project_id: "EMB_ex07"
    current_version: "v1.0"
    researcher: "DK"
