# >>>> Configuration 'README' >>>>
# >> General information >>
# This configuration file controls the behavior of the corresponding experiment workflow.
# One of the few "hard" constraints on the workflow is that this file is located
# in the same location as 'Snakefile' and 'scripts/'
# << General information <<

# >> Configuration >>
# Broadly, we split the configurable parameters of this workflow into 4 categories:
# 0) meta
# 1) network
# 2) experiment
# 3) workflow

# (0) meta
# These parameters control identifiers for resultant data.
# It is highly recommend you interface some external auto-increment tool,
# else this does not act as suitable "version control".

# (1) network
# Specify which networks should be ran as well as what layers.

# (2) experiment
# Here we add the "main" parameters in the experiment. These are properties of the procedure
# or tools used.
# Generally, "params" are parameters of research interest and will be sweeped over.
# "hyperparams" usually denote parameters that could have a non-negligible effect on results,
# however, there may not be a need/desire/intuition on their optimal values.

# (3) workflow
# These parameters are exclusively configurations on Snakemake and generated files.
# Changing them mostly comes down to researcher preference on file names.
# << Configuration <<

# >> Non-configurable >>
# The import of this file into the Snakemake workflow has to be hardcoded*.
# Do not rename this file or move anything.
# << Non-configurable <<
# <<<< Configuration 'README' <<<<
# =========================================
meta:
  project_id: "EMB_ex09-R"
  current_version: "v1.1"
  researcher: "DK"


network:
  # arxiv:
  #   alpha: [1, 2, 3] #, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  #   beta: [2, 3, 4] #, 5, 6, 7, 8, 9, 10, 11, 12, 13]
  celegans:
    alpha: [1, 2]
    beta: [2, 3]
  # drosophila:
  #   alpha: [1, 2, 3, 4, 5, 6]
  #   beta: [2, 3, 4, 5, 6, 7]
  london:
    alpha: [1, 2]
    beta: [2, 3]


experiment:
  params:
    pfis: [0.05, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 0.95]
    metrics: ["inverse"] # "negexp"]
    repetitions: 1
    dimensions: [10,15,20,30,40,60,80,100,120]

  hyperparams:
    embedding:
      walk_length: 30
      num_walks: 100
      workers: 4
      window: 10
      min_count: 1
      batch_words: 4



workflow:
  pathing:
    input:
      raw: "{root}/data/input/raw"
      preprocessed: "{root}/data/input/preprocessed/real"
    output:
      raw: "{root}/data/output/raw"
      preprocessed: "{root}/data/output/processed/real"
    result:
      dataframe: "{root}/results/dataframes"
      figures: "{root}/results/plots"
      reports: "{root}/results/reports"
    scripts: "./scripts/"

  datafiles:
    input:
      duplex: "{dir}/duplex_system={{system}}.edgelist"
    output:
      observation: "{dir}/observed_pfi={{pfi}}_system={{system}}_alpha={{alpha}}_beta={{beta}}_rep={{rep}}.pkl"
      vectors: "{dir}/vectors_pfi={{pfi}}_dimension={{dimension}}_system={{system}}_alpha={{alpha}}_beta={{beta}}_rep={{rep}}.pkl"
      distances: "{dir}/distances_pfi={{pfi}}_dimension={{dimension}}_system={{system}}_alpha={{alpha}}_beta={{beta}}_rep={{rep}}.pkl"
      reconstruction: "{dir}/reconstruction_metric={{metric}}_pfi={{pfi}}_dimension={{dimension}}_system={{system}}_alpha={{alpha}}_beta={{beta}}_rep={{rep}}.pkl"
      record: "{dir}/record_metric={{metric}}_pfi={{pfi}}_dimension={{dimension}}_system={{system}}_alpha={{alpha}}_beta={{beta}}_rep={{rep}}.pkl"
    result:
      dataframe: "{dir}/dataframe_{project_id}{current_version}_{researcher}_{date}.parquet"
      report: "{dir}/report_{project_id}{current_version}_{researcher}_{date}.html"
      dag: "{dir}/dag_{project_id}{current_version}_{researcher}_{date}.svg"
      figures:
        scatter: "{dir}/scatter_{project_id}{current_version}_{researcher}_{date}.png"
