network:
  N: [1000]
  tau1: [2.1]
  tau2: [1.0]
  mu: [0.1]
  avg_k: [5]
  min_community: [1]
  prob: [1.0]
  pfi: [0.05, 0.33, 0.67, 0.95]

experiment:
  params:
    repetitions: 1
    largest_component: True
    distance: ["negexp"]
  embedding:
    dimensions: 128
    walk_length: 30
    num_walks: 200
    workers: 8
    window: 10
    min_count: 1
    batch_words: 4

workflow:
  datafiles:
    KEEP_EMBEDDINGS: True
    KEEP_DATAFRAME: True
    TEMPLATE_DF: "{project_id}{current_version}_{researcher}_{date}"
    TEMPLATE_VECTORS: "{tmp}/{name}-vectors_tau1={tau1}_tau2={tau2}_mu={mu}_prob={prob}_pfi={pfi}_repetition={repetition}"
  pathing:  # must be relative to workflow scripts/notebooks
    SRC: "../src/"
    TMP: "../.tmp/"
    RAW: "../results/raw/"
    PROCESSED: "../results/processed/"
    FIGURES: "../results/plots/"
  versioning:
    project_id: "EMB_ex04"
    current_version: "v1.0-DEBUG"
    researcher: "DK"