network:
  N: [10000]
  tau1: [2.1]
  tau2: [1.0]
  mu: [0.1, 0.2, 0.3, 0.4, 0.5]
  avg_k: [5]
  min_community: [5]
  prob: [1.0]
  pfi: [0.00, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 0.95]

experiment:
  params:
    repetitions: 100
    largest_component: True
    distance: ["inverse", "negexp"]
  embedding:
    dimensions: 128
    walk_length: 30
    num_walks: 100
    workers: 24
    window: 10
    min_count: 1
    batch_words: 4

workflow:
  datafiles:  # templates should not include extensions
    KEEP_EMBEDDINGS: False
    KEEP_DATAFRAME: True
    TEMPLATE_DF: "{project_id}{current_version}_{researcher}_{date}"

  pathing:  # must be relative to workflow scripts/notebooks
    TMP: "/tmp/EmbeddedNaive/"
    RAW: "../../results/raw/"
    PROCESSED: "../../results/processed/"
    FIGURES: "../../results/plots/"
  versioning:
    project_id: "EMB_ex04"
    current_version: "v5.0"
    researcher: "DK"
