metadata:
  id: "EMB_ex37"
  version: "v2.0"
  researchers: "DK"
  protocol: True
  protocol_path: "./procotol_EMB_ex37.md"

dev:
  logging:
    logfile: "log_{datetime.today().strftime('%Y%m%d')}.log"
    logmode: "w"
    loglevel: 10  # 0 = none, 10 = debug, 20 = info, 30 = warn, 40 = error, 50 = critical
    logformat: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console:
    tqdm: True
    warnings_filter: True
    console_loglevel: 30


hyperparameters:
  workflow:
    root: "../../../../"  # ex37 -> active -> operative -> workflow -> root

