metadata:
  id: "EMB_ex37"
  version: "v2.0"
  researchers: "DK"
  protocol: True
  protocol_path: "./procotol_EMB_ex37.md"

dev:
  logging:
    logfile: "log_{datetime.today().strftime('%Y%m%d')}.log"
    logmode: "w"
    loglevel: 10  # 0 = none, 10 = debug, 20 = info, 30 = warn, 40 = error, 50 = critical
    logformat: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console:
    tqdm: True
    warnings_filter: True
    console_loglevel: 30


hyperparameters:
  workflow:
    root: "../../../../"  # ex37 -> active -> operative -> workflow -> root

parameters:  # default to always including intercept, see logreg params
  features: [["emb"], ["deg"], ["emb", "deg"]]

  caches:  # check inclusion
    embedding: ["N2V", "LE"]
    PC: [True, False]
    dimensions: [128]
    N: [1000]
    t1: [2.1]
    t2: [1.0]
    mu: [0.1]
    kavg: [6]
    kmax: [31]

  logistic_regression:  # pass as kwargs
    fit_intercept: True
    solver: "newton-cholesky"
    penalty: "l2"

