network:
  gamma: [2.1] #, 2.5, 2.9, 3.5]
  mu: [0.1, 0.2, 0.3, 0.4, 0.5]

experiment:
  params:
    pfi: [0.00, 0.10, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 0.95]
    metrics: ["inverse", "negexp"]
    largest_component: False
    num_eigenvalues: 40

  hyperparams:
    repetitions: 5

workflow:
  # Paths must be relative to Snakefile
  pathing:
    raw_data: "../../data/input/preprocessed/synthetic/"
    preprocessed_data: "../../data/input/preprocessed/"

    temp: "../.tmp/"

    raw: "../../results/raw/"
    processed: "../../results/processed/"

    figures: "../../results/plots/"
    reports: "../../results/reports/"

    scripts: "scripts/"

  versioning:
    project_id: "EMB_ex06"
    current_version: "v2.0-mu"
    researcher: "DK"
