# ========================================
# String templates with Snakemake and YAML
# ========================================
# Strings in YAML file with single curly brackets {}
# must be formatted in Snakefile (read as f-strings)
# Double curly brackets {{}}, however, are read in
# the Snakefile as single brackets - the Snakemake wildcard format.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
global:
  directories:
    input:
      raw: "{root}/data/input/raw"
      preprocessed: "{root}/data/input/preprocessed"
    output:
      raw: "{root}/data/output/raw"
      preprocessed: "{root}/data/output/processed"
    results:
      dataframes: "{root}/results/dataframes"
      figures: "{root}/results/plots"
      reports: "{root}/results/reports"

  files:
    observations: "{in_pcsd_dir}/remnants_{tag}_system={{system}}_pfi={{pfi}}.pkl"
    embeddings: "{out_raw_dir}/embeddings_{tag}_system={{system}}_pfi={{pfi}}_method={{method}}" ???
    distances: "{out_raw_dir}/XXX"
    reconstructions: "{out_pcsd_dir}/XXX"
    performances: "{out_pcsd_dir}/XXX"
    records: "{results_df_dir}/XXX"
    figures: "{results_fig_dir}/XXX"
    rulegraphs: "{results_rep_dir}/XXX"


ex17:
  metadata:
    project_id: "EMB_ex17"
    current_version: "v1.0"
    researcher: "DK"

  parameters:
    pfis:
      start: 0.05
      stop: 0.95
      step: 0.05
    embedding:
      method: "N2V"
      parameters:
        walk_length:
          start: 10
          stop: 30
          step: 2
        num_walks: 100
        dimensions: 128
      hyperparameters:
        workers: 8
        window: 10
        min_count: 1
        batch_words: 4
    metrics: ["inverse"]